<html>
<head>
<title>Using Custom JavaScript Errors</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">使用自定义JavaScript错误</h1>
<blockquote>原文：<a href="https://javascript.plainenglish.io/using-custom-javascript-errors-39270273fc2b?source=collection_archive---------6-----------------------#2019-12-19">https://javascript.plainenglish.io/using-custom-javascript-errors-39270273fc2b?source=collection_archive---------6-----------------------#2019-12-19</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="44bb" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">以及为什么它们在编程时很有用</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/093e45934884dffae4590bd3dd1a417f.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*Guh3Vfrl5FVPRJ77"/></div></div><figcaption class="kr ks gj gh gi kt ku bd b be z dk">Photo by <a class="ae kv" href="https://unsplash.com/@billy_pasco?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Billy Pasco</a> on <a class="ae kv" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></figcaption></figure><p id="5a08" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">您应该对这段代码很熟悉:</p><pre class="kg kh ki kj gt ls lt lu lv aw lw bi"><span id="5a8d" class="lx ly iq lt b gy lz ma l mb mc">function validateUser({ userId, password }) {<br/>  try {<br/>    axios.post('https://my-login-endpoint', { userId, password });<br/>  } catch (e) {<br/>    if (e.response.status === 400) {<br/>      displayError(e.response.data.detail);<br/>    } else {<br/>      displayError("Something went wrong."); // Generic error<br/>    }<br/>  }<br/>}</span></pre><p id="99a2" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">displayError是一个自定义函数，我假设您已经编写了这个函数，它要么直接在模态中显示错误，要么如果您正在使用React，它会调度另一个动作，将您的一个reducers中的Error属性设置为<code class="fe md me mf lt b">e.response.data.detail</code>或相应的一般错误。如果您正在使用<code class="fe md me mf lt b">redux-saga</code>，这种try catch模式尤其常见。唯一的区别是这个函数是一个生成器函数。</p><p id="820d" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">但是假设<code class="fe md me mf lt b">userId</code>只能是一个UUID/GUID。如果输入的用户Id不是有效的UUID，那么向端点发送请求值得吗？显然不是因为我们意识到它将被拒绝，当我们知道响应是什么时，增加服务器负载是徒劳的。那么我们检查一下<code class="fe md me mf lt b">userId</code>是否是有效的UUID，如果不是，我们用我们选择的字符串调用<code class="fe md me mf lt b">displayError</code>。这很容易做到，但这不是最佳的软件设计，因为我们已经有了显示错误的逻辑，为什么不使用它呢？但是如果我们<code class="fe md me mf lt b">throw new Error()</code>如果<code class="fe md me mf lt b">userId</code>不是一个有效的UUID会发生什么呢？我们将得到著名的javascript错误:<code class="fe md me mf lt b">Cannot read property status of undefined</code>，因为<a class="ae kv" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" rel="noopener ugc nofollow" target="_blank">错误对象</a>没有响应属性。所以这是一个自定义错误的好用例。这是一种简单的方法:</p><pre class="kg kh ki kj gt ls lt lu lv aw lw bi"><span id="a415" class="lx ly iq lt b gy lz ma l mb mc">function validateUser({ userId, password }) {<br/>  try {<br/>    if (!isValidUUID(userId)) {<br/>      const badRequestError = new <strong class="lt ir"><em class="mg">Error</em></strong>('BadRequest');<br/>      badRequestError.response = {<br/>        status: 400,<br/>        data: {<br/>          detail: 'Please enter a valid UUID!'<br/>        }<br/>      };<br/>      throw badRequestError;<br/>    }<br/>    axios.post('my-endpoint', { userId, password });<br/>  } catch (e) {<br/>    if (e.response.status === 400) {<br/>      displayError(e.response.data.detail);<br/>    } else {<br/>      displayError("Something went wrong."); // Generic error<br/>    }<br/>  }<br/>}</span></pre><p id="eb94" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">上面的代码满足条件<code class="fe md me mf lt b">e.response.status === 400</code>，因此我们使用<code class="fe md me mf lt b">displayError</code>函数的错误细节。</p><p id="c318" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">显然，最好的方法是在用户表单中进行验证，并保持“登录”按钮禁用，直到用户输入有效的UUID。但是，如果您必须调用API来验证请求是否会失败呢？例如，如果您必须先执行google recaptcha函数，然后调用您的登录API。在表单输入的onchange处理程序上调用google-recaptcha端点是不可行的，最好留给表单的submit函数。在这里，您可以调用google-recaptcha函数，并相应地选择是要命中登录API端点还是只显示一个错误。</p><p id="bd3d" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">我希望你觉得这很有用。请关注我，了解更多类似的内容以及软件的商业应用。下次见！</p></div></div>    
</body>
</html>